# Generated by Django 5.0.1 on 2024-01-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insights',
            name='added',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insights',
            name='published',
            field=models.CharField(max_length=255),
        ),
    ]
