# Generated by Django 5.0.1 on 2024-01-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_insights_added_alter_insights_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insights',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
