# Generated by Django 5.0.1 on 2024-01-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_insights_intensity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insights',
            name='added',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='country',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='insight',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='intensity',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='likelihood',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='pestle',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='published',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='region',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='relevance',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='source',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='title',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='url',
        ),
        migrations.AddField(
            model_name='insights',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
